### ISSUE TITLE
prot2dna

### ISSUE THREAD

**Issue by nathanhaigh** [csiro-crop-informatics/biokanga-manuscript#41]
Have you thought about protein to dna alignment? E.g. using `spaln` (https://github.com/ogotoh/spaln)?

**Comment by rsuchecki** [comment]
At some point I even tried to encourage someone to write a new prot2dna aligner as I found spaln a bit frustrating. Also I could not find many (any?) real alternatives so not much to compare. If there are a few, it may be tidier to have that as a separate benchmarking system as this one may get too complex.
